name: Push and Pull request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  local_test_job:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'